### ISSUE TITLE
/Scripts/Angular/dist/index.html not found. Details: Scripts/Angular/README.md

### ISSUE THREAD

**Issue by HamedBagheri1992** [ActiveDbSoft/active-query-builder-3-asp-net-samples-csharp#1]
angular method (JavaScript Project) can not run, all the method run successfully except this
if your project work, please complete your Readme.md file
thanks a lot

**Comment by ActiveDbSoft** [comment]
Hello, Hamed.
Thank you for your interest in Active Query Builder, for your feedback and sorry for the late response.
I am not sure what exactly had happened on your side, but we faced with the problems of Visual Studio being not able to parse typescript code in the Angular project. This problem is corrected now. If the problem was different and still exist on your side, please reply.
